import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-neutral-700`}
      >
        {children}
        <footer>
          <p className=" text-ice_pink text-center my-6 text-sm ">Designed & Developed By <Link href="/" className="hover:text-ice_yellow cursor-pointer">Nitish Sharma</Link>.</p>
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
